name: heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: akhileshns/heroku-deploy@master # This is the action
        with:
          heroku_api_key: "HRKU-6e49f9ed-90ad-437a-90fd-627a2514484a" #${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "appsrereerdddkcve01" #Must be unique in Heroku
          heroku_email: "tliro8iju1@mx.lknemail.dns-dynamic.net" #${{secrets.HEROKU_EMAIL}}
          usedocker: true
